### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by yohannes2025** [yohannes2025/project-planning-demo#1]
**User story**

- [ ] I want to ...

**Acceptance Criteria**

- [ ] home page - upcoming events
- [ ] event listing
- [ ] responsive list

**Tasks**

- [ ] Add html section on home page
- [ ] style the event using bootstrap
- [ ] add some samples
